"""Add likes and comments tables

Revision ID: 515801aa274b
Revises: 021ef86c4877
Create Date: 2025-09-09 22:26:04.496351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '515801aa274b'
down_revision: Union[str, Sequence[str], None] = '021ef86c4877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'user_id')
    )
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_filename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.add_column('videos', sa.Column('category', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('preview_filename', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('what', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('where', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('videos', 'status')
    op.drop_column('videos', 'rating')
    op.drop_column('videos', 'media_type')
    op.drop_column('videos', 'where')
    op.drop_column('videos', 'what')
    op.drop_column('videos', 'preview_filename')
    op.drop_column('videos', 'filename')
    op.drop_column('videos', 'category')
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'avatar_filename')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username')
    op.drop_table('likes')
    op.drop_table('comments')
    # ### end Alembic commands ###
